// studentData.js
export const studentData = [
    {
      id: 1,
      name: 'John Doe',
      ticketNumber: 'T123',
      ratingGrade: 90,
      examGrade: 80,
      comments: 'Good effort',
    },
    {
      id: 2,
      name: 'Jane Smith',
      ticketNumber: 'T124',
      ratingGrade: 85,
      examGrade: 75,
      comments: 'Needs improvement',
    },
    {
      id: 3,
      name: 'Alice Johnson',
      ticketNumber: 'T125',
      ratingGrade: 95,
      examGrade: 85,
      comments: 'Excellent work',
    },
    {
      id: 4,
      name: 'Bob Brown',
      ticketNumber: 'T126',
      ratingGrade: 80,
      examGrade: 70,
      comments: 'Needs more practice',
    },
    {
      id: 5,
      name: 'Emma Davis',
      ticketNumber: 'T127',
      ratingGrade: 85,
      examGrade: 90,
      comments: 'Showing improvement',
    },
    {
      id: 6,
      name: 'Grace Wilson',
      ticketNumber: 'T128',
      ratingGrade: 92,
      examGrade: 88,
      comments: 'Exceeding expectations',
    },
    {
      id: 7,
      name: 'Michael Brown',
      ticketNumber: 'T129',
      ratingGrade: 88,
      examGrade: 75,
      comments: 'Needs more focus',
    },
    {
      id: 8,
      name: 'Emily Jones',
      ticketNumber: 'T130',
      ratingGrade: 70,
      examGrade: 65,
      comments: 'Struggling with concepts',
    },
    {
      id: 9,
      name: 'David Clark',
      ticketNumber: 'T131',
      ratingGrade: 75,
      examGrade: 60,
      comments: 'Falling behind',
    },
    {
      id: 10,
      name: 'Sophia Martinez',
      ticketNumber: 'T132',
      ratingGrade: 85,
      examGrade: 75,
      comments: 'Needs more practice',
    },
  ];
  